### ISSUE TITLE
Generate models from database tables

### ISSUE THREAD

**Issue by bryan-vh** [supabase/supabase-swift#240]
# Feature request

I'm wondering if it's possible to generate model types (preferably structs) from the database tables. Is there any effort to implement this or is assumed that API consumers will have to create their own models from scratch to mimic the tables on the backend?

**Comment by grdsdev** [comment]
Hi @bryan-vh,

We don't support this yet, but it is on the radar.

I'll keep the issue open, and post updates here once we have any.

Thank you!

**Comment by grdsdev** [comment]
Quick update on this:

I'm working on a generator for Swift on https://github.com/supabase/postgres-meta/pull/779, for now, it only generates plain Swift structs that can be used to encode/decode Postgres Response.
