### ISSUE TITLE
Query parameter while invoking edge functions

### ISSUE THREAD

**Issue by GitNirajHub** [supabase/supabase-swift#255]
# Feature request

Can we have query parameter option while invoking an function from swift client

## Is your feature request related to a problem? Please describe.

I made an edge get function to get a value against an key that to be passed in query params, but there is no options to use query params in swift client

## Describe the solution you'd like

```
Supabase.client.functions.invoke(
            String,
            queryItems: [URLQueryItem]
            options: FunctionInvokeOptions(
                method: FunctionInvokeOptions.Method?,
                headers: [String : String],
                body: Encodable)) { Data, HTTPURLResponse in
                    
        }
   ```     

## Describe alternatives you've considered

NA

## Additional context

NA

**Comment by grdsdev** [comment]
Hi @GitNirajHub 

You can pass the query together with the `functionName` parameter for now.

```swift
functions.invoke("function?key=value")
```

I know this isn't the best solution, so I'll talk with the team and see how we can approach this, as this feature also isn't supported on the other client libraries.

For now, try the example I mentioned and I'll get back to you with a proper approach.

Thanks.

**Comment by grdsdev** [comment]
@GitNirajHub I'm adding a new `query: [URLQueryItem]` param to the invoke options that should be used to pass query parameters to the function invocation.
