### ISSUE TITLE
Release Number

### ISSUE THREAD

**Issue by thecoolwinter** [supabase/supabase-swift#3]
### Bug report

Is there any chance we could create a new release with version 0.0.1 or something small? It would help when integrating this package with other packages where SPM requires a version number.

**Comment by satishbabariya** [comment]
Hey @thecoolwinter, there is some functionally remain in Postgrest client for swift to be implemented mainly rpc part. once I'm done with it will do testing and one alpha release of all things.

**Comment by thecoolwinter** [comment]
@satishbabariya Sounds good 🤙🏻
