### ISSUE TITLE
Failing to decode models when querying foreign tables

### ISSUE THREAD

**Issue by bstillitano** [supabase/supabase-swift#322]
# Bug report

## Describe the bug

When providing a `.select` modifier that points to a foreign table, values fail to decode.

## To Reproduce

**Models**
```
struct Transaction: Codable {
    var id: UUID
    var name: String
    var subtitle: String?
    var merchant: String?
    var amount: Decimal
    var tax_deductible: Bool = false
    var date: Date
    var account: TransactionAccount?
}

enum AccountType: String, Codable, CaseIterable {
    case debit
    case savings
    case loan
    case credit
    case cash
}

struct TransactionAccount: Codable, Hashable {
    var id: UUID
    var name: String
    var description: String?
    var type: AccountType
    var color: String
}
```

**SDK Usage**
```
do {
            return try await Database.shared
                .client
                .database
                .from("transactions")
                .select("*, account(*)")
                .in("type", value: scope.transactionTypes.map({ $0.rawValue }))
                .execute()
                .value
        } catch {
            return []
        }
```

**Swift Error**
```
Printing description of error:
▿ DecodingError
  ▿ typeMismatch : 2 elements
    - .0 : Swift.Dictionary<Swift.String, Any>
    ▿ .1 : Context
      ▿ codingPath : 2 elements
        ▿ 0 : _JSONKey(stringValue: "Index 2", intValue: 2)
          ▿ rep : Rep
            - index : 2
        - 1 : CodingKeys(stringValue: "account", intValue: nil)
      - debugDescription : "Expected to decode Dictionary<String, Any> but found a string instead."
      - underlyingError : nil
```

## Expected behavior

The docs make it clear that I should be able to do this and get back the full object from the foreign table. https://supabase.com/docs/reference/swift/select?example=querying-foreign-table-with-count

## Additional context

If I add every value to my query individually, the request works as expected:
```
do {
            return try await Database.shared
                .client
                .database
                .from("transactions")
                .select(
                """
            id,
            description,
            amount,
            type,
            date,
            name,
            tax_deductible,
            account(*)
            """
            )
                .in("type", value: scope.transactionTypes.map({ $0.rawValue }))
                .execute()
                .value
        } catch {
            return []
        }
    }
```

**Comment by bstillitano** [comment]
Digging a little deeper into this, it seems like the value being decoded, is not the value being returned from the server. Looking at the response from the url request, I can see that it is not the value that `execute().data` returns.

![Screenshot 2024-04-03 at 3 05 45 pm](https://github.com/supabase-community/supabase-swift/assets/40552246/c6857d80-3fc4-4a55-854b-93e4c5a938c8)

**Comment by grdsdev** [comment]
Hi @bstillitano thanks for opening the issue, I'll investigate it.

The foreign key to account schema is named `account`, and then when you query for the `account(*)`, I think it breaks because the query result and the foreign key has the same name `account`. I'd suggest you rename the foreign key to something like `account_id` and then retry the same query using the `*,account(*)`.

While that, I'll investigate to check if there is any other issue.

Thanks again.

**Comment by bstillitano** [comment]
Thanks for getting back to me @grdsdev , I'm not quite sure how to do that. Are you able to point me in the right direction on how to do that? I can't see it in the GUI anywhere.

**Comment by grdsdev** [comment]
Sure, see the `account` column? Rename it to `account_id`, as it holds the reference for the account through its `id`.

**Comment by bstillitano** [comment]
@grdsdev have done that and get the following error:

```
{
  "code" : "PGRST200",
  "message" : "Could not find a relationship between 'transactions' and 'account' in the schema cache",
  "details" : "Searched for a foreign key relationship between 'transactions' and 'account' in the schema 'public', but no matches were found.",
  "hint" : "Perhaps you meant 'accounts' instead of 'account'."
}
```

For what it's worth:

1. Table is named `accounts`
2. Passing `account(*)` into the query (notice no `s` on the end)

**Comment by bstillitano** [comment]
Have just come across another odd tidbit, if you pass in two foreign keys, decoding fails also, for example:

```
func getTransactions(for recurringTransaction: UUID) async -> [Transaction] {
        do {
            return try await Database.shared
                .client
                .database
                .from("transactions")
                .select("id, description, amount, type, date, name, tax_deductible, parent(*), account(*)")
                .eq("parent", value: recurringTransaction)
                .order("date", ascending: false)
                .execute()
                .value
        } catch {
            return []
        }
    }
```

Will throw the following error:
```
▿ DecodingError
  ▿ typeMismatch : 2 elements
    - .0 : Swift.Dictionary<Swift.String, Any>
    ▿ .1 : Context
      ▿ codingPath : 3 elements
        ▿ 0 : _JSONKey(stringValue: "Index 0", intValue: 0)
          ▿ rep : Rep
            - index : 0
        - 1 : CodingKeys(stringValue: "parent", intValue: nil)
        - 2 : CodingKeys(stringValue: "account", intValue: nil)
      - debugDescription : "Expected to decode Dictionary<String, Any> but found a string instead."
      - underlyingError : nil
```

If I remove either the `parent(*)` or the `account(*)` part of my query, it works as expected.

**Comment by grdsdev** [comment]
When you pass `account(*)` it tries to loads the relationship for `account` schema which is wrong, as it is named `accounts`.

To fix that, you need to use field aliasing, use `account:accounts(*)` the first part before the `:` is the alias you want.

**Comment by grdsdev** [comment]
@bstillitano I hope that helped you, I'll be closing this issue for know, if you're still having issues with it, feel free to re-open it.

Thanks.

**Comment by bstillitano** [comment]
Apologies, this issue is unresolved. That didn't help, I've just had to provide the entire query as a string for now to work around this

**Comment by grdsdev** [comment]
@bstillitano can you provide me the full schema for the `transactions` and `account` table?

**Comment by grdsdev** [comment]
@bstillitano I was able to make it work by applying the following changes:

1. Rename the `account` column in the `transactions` table to `account_id`.
```sql
alter table transactions rename column account to account_id;
```

2. Define your struct field as `var account: TransactionAccount?`
3. Query using `*,account:accounts(*)`

I'll chat with the team to add some best practices to the docs regarding the implementation of relationships.

Thanks.

**Comment by grdsdev** [comment]
Hi, hope the above made it work for you too, I'm closing this issue for now, but feel free to re-open it if needed.

Thanks.

**Comment by stanifert** [comment]
@bstillitano Hello, were you able to resolve your issue with the above guidance? I believe I am experiencing the same or a similar issue.

I have:

- Table named `agencies`

- Table named `launches` with column 'provider' containing an agency id (int), linked via foreign key to `id` column of the `agencies` table


When I query via `.select(*)`, the "provider" value is the raw ID (int) as expected

When I query via `.select(*, agencies(*)` following the [docs](https://supabase.com/docs/guides/database/joins-and-nesting?queryGroups=output-format&output-format=table&queryGroups=language&language=swift), the `provider` value is again the raw ID (int) and an additional property named "agencies" is added to the object response with a value of `null`.

When I query via `.select(*, provider:agencies(*))`, once again the `provider` property is the raw ID (int) and now a duplicate `provider` property is added to the object response with a value of `null`


@grdsdev Do you have any insights you could share?
