### ISSUE TITLE
rpc with different params type

### ISSUE THREAD

**Issue by therickys93** [supabase/supabase-swift#335]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to call the rpc method of the database client passing multiple params with different types. (compile error)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

- supabase-swift version: 2.6.0 (not tested with other versions)

```swift
  func insertEmployee(withName name: String, andAge age: Int) async throws {
      let supabase = SupabaseClient(supabaseURL: URL(string:"SUPABASE_URL")!, supabaseKey: "SUPABASE_ANON_KEY")
      let database = supabase.database
      try await database.rpc("insertnewemployee", params: ["name": name, "age": age]).execute()
  }
```

- compile errors:
    Conflicting arguments to generic parameter 'some Encodable & Sendable' ('[String : Int]' vs. '[String : String]')
    Conflicting arguments to generic parameter 'Value' ('Int' vs. 'String')

## Expected behavior

able to compile without these errors

## Screenshots

![Screenshot 2024-04-09 at 19 54 59](https://github.com/supabase/supabase-swift/assets/15905440/12f1164e-b823-46a8-8a49-2b0549674c2a)

## System information

os: [e.g., macos]
version of supabase-swift: [e.g., 2.6.0]
xcode version: Version 15.2 (15C500b)

**Comment by grdsdev** [comment]
Hi @therickys93 

The `rpc` method expects a parameter that conforms to the `Encodable` protocol, when you initialize a `Dictionary` using `["name": name, "age": age]` that gives you a `[String: Any]` type, that doesn't conform to `Encodable`.

You have two options to overcome this:

1. Use a `Encodable` struct
```swift
struct NewEmployee: Encodable {
    let name: String
    let age: Int
}

try await database.rpc(
    "insertnewemployee",
    params: NewEmployee(
        name: name,
        age: age
    )
).execute()
```

2. Use the `AnyJSON` convenience type
```swift
try await database.rpc(
    "insertnewemployee",
    params: [
        "name": AnyJSON.string(name),
        "age": AnyJSON.integer(age)
    ]
).execute()
```

This behavior isn't a bug, so I hope the above helps you.

Thanks.

**Comment by therickys93** [comment]
Hi @grdsdev thanks so much for your fast reply. Your suggestion helps me a lot also understanding how it works.

What I suggest is to include an example like this one in the documentation on the docs site so it is more clear to anybody to understand it better.

**Comment by grdsdev** [comment]
@therickys93 we're planning a massive update on the Swift docs, will make sure we cover this too.

Thanks for the feedback, and let me know if you need anything.

**Comment by grdsdev** [comment]
Example added in: https://github.com/supabase/supabase/pull/22625
