### ISSUE TITLE
Insert a todo into the database example throws an error. Suggested fix.

### ISSUE THREAD

**Issue by AndrewMayneProjects** [supabase/supabase-swift#4]
# Bug report

## Describe the bug

The code for adding a Todo throws several errors.

There appears to be an error in the JSON serialization and the client database insertion says "from" when the method should be "form. Changing that part works. But I'm unsure if the data is being properly serialized.

     do {
            let jsonData: Data = try JSONEncoder().encode(todo)
            let jsonDict  = try JSONSerialization.jsonObject(with: jsonData, options: .allowFragments)
            try client.database.form("todos")
                .insert(values: jsonDict as! [String : Any])
                               .execute { results in
                                
                                
                                print(results)
                // Handle response
            }
        } catch {
           print("Error inserting the todo: \(error)")
        }

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Add the example for adding a Todo.

The following error messages appear:

- Cannot convert value of type 'Any' to specified type '[String : Any]'
- Closure expression is unused
- Unable to infer type of a closure parameter 'results' in the current context

## Expected behavior

Ideally the code wouldn't throw any error messages.

## System information

- Xcode 12.5.1

**Comment by satishbabariya** [comment]
@AndrewMayneProjects fixed misspelled from and also fixed the serialisation issue. here is the example:

```swift
struct Todo: Codable {
    var `id`: Int?
    var task: String?
    var completed: Bool?
}

database.from("todo").select().execute { (result) in
    switch result {
    case .success(let response):
        guard let data = response.body as? Data else {
            return
        }
        do {
            let todos = try JSONDecoder().decode([Todo].self, from: data)
            print(todos)
        } catch {
            print(error.localizedDescription)
        }
    case .failure(let error):
        print(error.localizedDescription)
    }
}

do {
    let todo = Todo(task: "fix some issues in postgrest-swift", completed: true)
    let jsonData: Data = try JSONEncoder().encode(todo)
    
    database.from("todo").insert(values: jsonData).execute { (result) in
        switch result {
        case .success(let response):
            guard let data = response.body as? Data else {
                return
            }
            do {
                let todos = try JSONDecoder().decode([Todo].self, from: data)
                print(todos)
            } catch {
                print(error.localizedDescription)
            }
        case .failure(let error):
            print(error.localizedDescription)
        }
    }
    
}catch {
    print(error.localizedDescription)
}
```
ref: https://github.com/supabase/postgrest-swift/blob/master/Sources/example/main.swift

**Comment by AndrewMayneProjects** [comment]
This works great! Thank you!
