### ISSUE TITLE
Equals filter failed on column where value starts with non-alphanumeric character

### ISSUE THREAD

**Issue by otymartin** [supabase/supabase-swift#401]
@grdsdev 

## Describe the bug

When filtering a column using `equals` where the value is an `e.164` formatted phone number starting with the character `+`, my query returns with an empty array.

## To Reproduce
This query works in the dashboard
`SELECT
  *
FROM
  friend_invites
WHERE
  "to" = '+16505555555';
  `

But in my swift client side query, it returns an empty array. I had to edit the table column and remove the "+" in `+16505555555` for this same query to work.
```
let invites: [FriendInvite]= try await database
                .from("friend_invites")
                .select()
                .eq("to", value: "+16505555555")
                .execute()
                .value
```

Is this expected behaviour as in is "+" a reserved character or is this a bug?

- OS: iOS
- Xcode: 15
- Version of supabase-swift: 2.11.0

**Comment by grdsdev** [comment]
Thanks @otymartin for opening this issue, this is a bug, and it was fixed some time ago but got lost.

I'm patching the fix again.

**Comment by otymartin** [comment]
Thanks @grdsdev 🙏
