### ISSUE TITLE
Bug: Unable to use Apple Sign in with some ids

### ISSUE THREAD

**Issue by pradeepb28** [supabase/supabase-swift#425]
It seems like some Apple Sign in ids receiving the following error consistently on our customer side. I was able to reproduce the same with one of my Apple id as well but not for the other id. I am not sure if it is related to SDK or supabase backend side.

My current setup looks like this 
![CleanShot 2024-06-26 at 10 18 47](https://github.com/supabase/supabase-swift/assets/6823101/b822060e-cf63-48ee-96b9-7d2ce1754711)

- I've made sure Apple sign in is enabled on supabase dashboard 
![CleanShot 2024-06-26 at 10 16 44](https://github.com/supabase/supabase-swift/assets/6823101/3ee823d9-ecd8-4a75-b540-aa13efd398a7)

- this is where it fails
![CleanShot 2024-06-26 at 10 39 24](https://github.com/supabase/supabase-swift/assets/6823101/702c7ce4-6664-4739-b081-9c1d888944d4)

**Error**
▿ Auth.AuthError.api
  ▿ api: Auth.AuthError.APIError
    - msg: nil
    - code: nil
    ▿ error: Optional("server_error")
      - some: "server_error"
    ▿ errorDescription: Optional("Internal Server Error")
      - some: "Internal Server Error"
    - weakPassword: nil

**Comment by grdsdev** [comment]
Hi @pradeepb28 

Can you [open a support ticket](https://supabase.com/dashboard/support/new) so we can investigate this internally, based on the error message returned, it is difficult to find out the problem.

Post the ticket number here and I can investigate it internally, thanks.

**Comment by pradeepb28** [comment]
> open a support ticket

@grdsdev Ticket# nfyydhypalwhxsybpifd

**Comment by grdsdev** [comment]
Resolved internally. Posting the solution here if someone faces similar issues.

> Since the auth service relies on the auth schema, any triggers / functions you have on any of those tables that fail will result in the auth service returning a 500 error. This is because the auth service won't be able to complete the transaction.
