### ISSUE TITLE
Verify and log in through OTP - Documentation Error or Feature Missing?

### ISSUE THREAD

**Issue by NicolasAlmerge** [supabase/supabase-swift#446]
# Improve documentation

## Link 

https://supabase.com/docs/reference/swift/auth-verifyotp

## Describe the problem

According to the documentation, a `token_hash` parameter can be passed in to the method (in which case, the `email` or `phone` parameters are not needed). However, the Swift client SDK doesn't allow that.

## Describe the improvement

Add a `verifyOTP(tokenHash: String)` method (similar to JS), or update the docs.

**Comment by grdsdev** [comment]
Thanks @NicolasAlmerge for pointing out all this mistake, the method is missing from Swift lib, I'll add it ASAP.

Thanks again.

**Comment by NicolasAlmerge** [comment]
You're welcome, thanks for updating! Following Swift's naming conventions, it would be more logical to call the parameter `tokenHash` instead of `token_hash` (and update the name in the docs too).
