### ISSUE TITLE
Crash when using RealtimeV2

### ISSUE THREAD

**Issue by MilesV64** [supabase/supabase-swift#469]
I'm facing a crash within RealtimeV2 while just leaving our app open. The app uses realtime on each screen, and when opening each screen we connect the RealtimeV2 client if needed like so:

```swift
let client = UserController.shared.supabaseClient.realtimeV2

if client.status == .disconnected {
    await client.connect()
}

// subscribe to channel etc
```

We never call `disconnect()`. However after leaving the app open, after anywhere between 5 minutes to hours the RealtimeV2 library encounters the crash `Fatal error: attempt to await next() on more than one task`

![Frame 1](https://github.com/user-attachments/assets/14c7036a-c59c-4817-8c0c-d53fd94bae26)
![Frame 2](https://github.com/user-attachments/assets/617d606d-cb2c-49e6-9591-e697568261a3)

Seems this line `for await connectionStatus in ws.connect()` needs to be used very carefully. I am struggling to reproduce manually but maybe something to do with only setting `status = .connecting` after the `Task.sleep` leading to this potentially getting called twice if you were to call `connect(reconnect: true)` twice somehow?

**Comment by MilesV64** [comment]
Got a consistent, manual repro!

```swift
let client = UserController.shared.supabaseClient.realtimeV2

Task {
    await client.connect()
}

Task {
    await client.connect()
}
```

In normal usage I think this can happen if calling connect in just one task but maybe a reconnect is happening at the same time.

**Comment by grdsdev** [comment]
Hi @MilesV64  thanks for opening the issue, I'll investigate and keep you updated.

**Comment by EduardMe** [comment]
We are seeing this too with channels:

```swift
Task {
	// Fully re-subscribe to the channel, otherwise notifications might stop after longer sleep phases
	let channels = await supabase.channels
	let status = supabase.realtimeV2.status
	
	guard status == .disconnected && channels.isEmpty else { return }
	
	let channel = await supabase.channel("any")
	let changeStream = channel.postgresChange(
		AnyAction.self,
		schema: "public",
		table: "notes"
	)
	
	await channel.subscribe()

[...]
```

We even check if it's disconnected and the list of channels is empty. It seems it can disconnect if the app runs for a while and internet connection is off during macOS sleeps or so, but the await is still running.

Or is there a more reliable way to trigger a reconnect if needed?
