### ISSUE TITLE
Command SwiftCompile failed with a nonzero exit code

### ISSUE THREAD

**Issue by alexe100** [supabase/supabase-swift#485]
# Bug report

Xcode Version 14.3.1 (14E300c)
Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)

The steps:
Created new iOS APP project (SwiftUI)
   Product | Build. => OK
File | Add Packages | https://github.com/supabase/supabase-swift
Dependency Rule: Up To Next Major Version 2.0.0 < 3.0.0 | Add Package
Then selected all packages

 Product | Build. => Command SwiftCompile failed with a nonzero exit code

## System information

- OS: macOS Ventura 13.3.1
- Version of Node.js: v20.11.1

**Comment by grdsdev** [comment]
Hi, Swift 5.8 isn't supported, please use >=5.9

Thanks.
