### ISSUE TITLE
X-Client-Info

### ISSUE THREAD

**Issue by awalias** [supabase/supabase-swift#5]
we're rolling out a header similar to Stripe's App-Data in all of the client libs so issues can be debugged more easily between the client and the backend

the javascript libs are done already: supabase/supabase-js#238

the format is: X-Client-Info: supabase-js/1.11.0

for client libs that wrap others (like how supabase-js wraps gotrue-js) we allow the wrapper lib to overwrite the wrapped lib's header (given that we can infer the gotrue-js version based on which supabase-js was used to make the call)

any help with rolling this out here would be incredible, it also ideally would be rolled out into the wrapped libs (postgrest-swift etc.)

**Comment by satishbabariya** [comment]
fixed: https://github.com/supabase/supabase-swift/commit/c9703d86b963cb7a4fbb3371b457532fa4802191

**Comment by awalias** [comment]
you rock @satishbabariya
