### ISSUE TITLE
AuthError error description should be exhaustive

### ISSUE THREAD

**Issue by peterkos** [supabase/supabase-swift#505]
# Chore

## Describe the chore

Given that every error is "known", it should be possible to **always** have an errorDescription. This is all correctly implemented, BUT errorDescription is still optional -- there is no reason to be optional if we never return `nil`, no?

https://github.com/supabase/supabase-swift/blob/4c966eafaaebc893a418e6334ef67beb0287a9ad/Sources/Auth/AuthError.swift#L53-L65

## Additional context

This would allow for consistent error handling:
```swift

let supabaseResponse: Supabase.AuthResponse
do {
    supabaseResponse = try await client.auth.signUp(/* ... */)
} catch let error as AuthError {
    return .failure(.supabaseError(error.errorDescription))
} catch {
    return .failure(.supabaseError(error.localizedDescription))
}
```

Versus currently, where this workaround is needed:

```swift

let supabaseResponse: Supabase.AuthResponse
do {
    supabaseResponse = try await client.auth.signUp(/* ... */)
} catch let error as AuthError {
    return .failure(.supabaseError(error.errorDescription ?? "Who the hell knows what happened"))
} catch {
    return .failure(.supabaseError(error.localizedDescription))
}
```

Ideally once Swift 6 comes out, **typed throws** are implemented too but that's probably best for a separate issue :)

**Comment by grdsdev** [comment]
Hi, I understand it but the `errorDescription` here is the `LocalizedError'`'s protocol requirement, and it is defined as optional. So, not sure how we can improve on that.

**Comment by peterkos** [comment]
Oh! Apllogies -- I was looking at `Error`'s protocol, not `LocalizedError`. Good point!

Maybe this could be folded in as part of #396? Ideally the callee could `switch` through error code options and get a nice code / userFriendlyDescription or something like that imo.

**Comment by grdsdev** [comment]
Hi @peterkos I refactored the whole `AuthError` type, and added support for error codes in the [PR](https://github.com/supabase/supabase-swift/pull/518).

I'd appreciate if you could take it for a spin, and let me know if that improves error handling for you.

**Comment by grdsdev** [comment]
I'll consider this got fixed by https://github.com/supabase/supabase-swift/pull/518
