### ISSUE TITLE
Experimental `functions._invokeWithStreamedResponse` never yields data

### ISSUE THREAD

**Issue by kirkbyo** [supabase/supabase-swift#523]
# Bug report

## Describe the bug

When utilizing the experimental `functions. _invokeWithStreamedResponse` method (introduced in https://github.com/supabase/supabase-swift/pull/346), the returned `AsyncThrowingStream` never yields any data to the consumer.

```swift
let events = supabase.functions._invokeWithStreamedResponse("some-sse-edge-function", options: options)
for try await data in events {
   // never executed
}
```

## To Reproduce

Initialize `_invokeWithStreamedResponse` with an edge-function configured to send a text stream (e.g. the [Deno SSE template](https://deno.com/blog/deploy-streams#server-sent-events) should suffice).

## Expected behavior

As bytes are decoded from the underlying `NSURLSession` they are yielded to the consumer.

## System information

- OS: macOS 14.4.1
- Version of supabase-swift: 2.13.2
- iOS version: 17.0.1

## Additional context

The current implementation of `_invokeWithStreamedResponse` creates a `session.dataTask` with a callback:

https://github.com/supabase/supabase-swift/blob/fa8db0c4ca07910a03536f81b74c556db5de1e97/Sources/Functions/FunctionsClient.swift#L201-L217

however, it is also specifying a `URLSession` delegate which is responsible for yielding data: 

https://github.com/supabase/supabase-swift/blob/fa8db0c4ca07910a03536f81b74c556db5de1e97/Sources/Functions/FunctionsClient.swift#L197

According to the [docs](https://developer.apple.com/documentation/foundation/urlsession/1407613-datatask), if a `dataTask` is specified with a callback, then the delegate is never used, which would explain why values are never yielded:

> By using the completion handler, the task bypasses calls to delegate methods for response and data delivery, and instead provides any resulting [NSData](https://developer.apple.com/documentation/foundation/nsdata), [URLResponse](https://developer.apple.com/documentation/foundation/urlresponse), and [NSError](https://developer.apple.com/documentation/foundation/nserror) objects inside the completion handler. Delegate methods for handling authentication challenges, however, are still called.

Patching the library to no longer use the callback resolved my issue: https://github.com/kirkbyo/supabase-swift/commit/70959a37a3cdeeab8f97a62be7a01bf1c9b1f84d

**Comment by grdsdev** [comment]
Thanks for reporting @kirkbyo 

Feel free to open a PR with your fix.
