### ISSUE TITLE
Docker Build Swift error

### ISSUE THREAD

**Issue by Th3F0x-code** [supabase/supabase-swift#534]
### Discussed in https://github.com/orgs/supabase/discussions/29160

<div type='discussions-op-text'>

<sup>Originally posted by **Th3F0x-code** September  8, 2024</sup>
when I try to compile my package using a ubuntu image I always get this error while if I compile on macOS I get no error:
```
/build/Sources/App/db.swift:53:59: error: type 'AuthClient.Configuration' has no member 'defaultLocalStorage'
auth: .init(storage: AuthClient.Configuration.defaultLocalStorage),
 ~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
 error: fatalError

```

this is the piece of code that generates the error:

```
#if !os(Linux)
        let options = SupabaseClientOptions(db: .init(schema: "public"), auth: .init(redirectToURL: Constants.redirectToURL) ,global: .init(logger: ConsoleLogger()))
#else
        let options = SupabaseClientOptions(
            db: .init(schema: "public"),
            auth: .init(storage: AuthClient.Configuration.defaultLocalStorage),
            global: .init(logger: ConsoleLogger())
        )
#endif
```

 any ideas?

</div>

**Comment by grdsdev** [comment]
Hi @Th3F0x-code, the package doesn't have a default instance for local storage on Linux platform, thats why you get the `error: type 'AuthClient.Configuration' has no member 'defaultLocalStorage'`.

You need to provide your own implementation.
