### ISSUE TITLE
Compiled module was created by a different version of the compiler '5.10.0.13'

### ISSUE THREAD

**Issue by bring-shrubbery** [supabase/supabase-swift#536]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After updating to macOS 15.0 Sequoia, updating Xcode and trying to re-build my project, I'm getting the following error:

```
Compiled module was created by a different version of the compiler '5.10.0.13'; rebuild 'Supabase' and try again: /Users/antoni/Library/Developer/Xcode/DerivedData/[project-name]/Index.noindex/Build/Products/Debug-iphoneos/Supabase.swiftmodule/arm64-apple-ios.swiftmodule
```

## To Reproduce

1. Create project in macOS 15.0 Sequoia in Xcode 16.0.
2. Add supabase-swift to that project.
3. Select target device with iOS 18.0.

## Expected behavior

Should just build without errors on latest macOS/Xcode versions.

## System information

- OS: macOS 15.0 Sequoia, Xcode 16.0
- Version of supabase-swift: 2.18.0

## Additional context

I'm pretty sure this is solvable by just rebuilding the project without any changes using the latest Xcode?

**Comment by bring-shrubbery** [comment]
Just realised, this issue should be fixed if #468 is merged.

**Comment by grdsdev** [comment]
Hi @bring-shrubbery, the library should work fine with macOS 15.0 Sequoia and Xcode 16.0.

Please, try to clean your DerivedData folder and do a clean build of your project.

**Comment by bring-shrubbery** [comment]
Hey @grdsdev

You're correct, after force-cleaning DerivedData it worked! Thanks for help, and sorry for unnecessary issue 🙏

**Comment by Wangggym** [comment]
<img width="869" alt="image" src="https://github.com/user-attachments/assets/108aa0ee-aba4-427e-adc8-d0123862f819">
it does not work for me, clean the DerivedData folder and do a clean build

**Comment by grdsdev** [comment]
@Wangggym that isn't Supabase package.
