### ISSUE TITLE
ErrorCode is missing invalid_grant

### ISSUE THREAD

**Issue by c128128** [supabase/supabase-swift#543]
`ErrorCode` is missing `invalid_grant`

**Comment by grdsdev** [comment]
Hi @c128128 `invalid_grant` is not a valid error code, check list in backend definition: https://github.com/supabase/auth/blob/ba00f75c28d6708ddf8ee151ce18f2d6193689ef/internal/api/errorcodes.go

**Comment by c128128** [comment]
And why then I am getting it ? Steps to reproduce:
1. Register a new user, using swift sdk.
2. Delete that user from database. (manually)
3. Login with the same user.
4. `invalid_grant` response, in swift will be unknown.

**Comment by grdsdev** [comment]
Could you paste the exact response you get in step 4?

I'm trying to reproduce by following those steps, but I get a `invalid_credentials` code in the 4th step, which is a valid code.

**Comment by c128128** [comment]
Thank you for your reply.

It seems that the issue is due to my self-hosted Supabase being a few versions outdated.

**Comment by c128128** [comment]
I have updated my server with last supabase, looks like this error still exists. Here is the exact error from the response:
```
{
	"error": "invalid_grant",
	"error_description": "Invalid login credentials"
}
```
