### ISSUE TITLE
Cache control not applied when uploading files

### ISSUE THREAD

**Issue by florian-mlr** [supabase/supabase-swift#550]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have noticed an issue regarding the "Cache-Control" header. After uploading an image and explicitly specifying the "cacheControl" option, I find that when I subsequently retrieve the image, the header does not include the intended "Cache-Control" configuration. Instead, it appears that the cache control is set to "no-cache."

```
try await NetworkClient.shared.storage
            .from("photos")
            .upload(
                path: "\(userId)/\(photoName).\(fileExtension)",
                file: data,
                options: FileOptions(
                    cacheControl: "172800",
                    contentType: "image/jpeg"
                )
            )
```

## To Reproduce

Upload an image and set the cache control
When fetching the uploaded image, the header contains "Cache-Control: no-cache"

## Expected behavior

When fetching the uploaded image, the header should contains "Cache-Control: max-age=172800"

## System information

- OS: iOS 17.4
- Version of supabase-swift: 2.8.1

## Additional context

I also want to mention that I tried updating the library to v2.20.0 to check if the issue is resolved. However, when I proceeded with the update, I encountered an error: "error: errSecItemNotFound: The item cannot be found." Due to this error, I decided to abandon the migration.

**Comment by grdsdev** [comment]
Hi @florian-mlr thansk for the report.

Regarding cache control, I was able to reproduce it, I'm checking with backend, the lib seems to be correctly sending the request.

About `error: errSecItemNotFound` error you got when updating the library, does it break anything for you? Or is it just the log message?

**Comment by florian-mlr** [comment]
> Hi @florian-mlr thansk for the report.
> 
> Regarding cache control, I was able to reproduce it, I'm checking with backend, the lib seems to be correctly sending the request.

Hey @grdsdev , thank you for the quick reply

How do you log headers ?
I thought it came from the library because I have an android app where I created my own network library and when I send the cache control in the header, I can see that my image has the expected cache control.

> 
> About `error: errSecItemNotFound` error you got when updating the library, does it break anything for you? Or is it just the log message?

Yes it breaks the logic in my app, the error is thrown when i make this call `try await NetworkClient.shared.auth.session` 
and I treat this error as an undefined error, I would have preferred to receive an error like `AuthError.sessionNotFound`

**Comment by florian-mlr** [comment]
Hello @grdsdev 
When do you plan to release the fix ?

**Comment by florian-mlr** [comment]
In the meantime i've created my own function : 

```
static func uploadImage(
        bucket: String,
        path: String,
        data: Data,
        upsert: Bool = false,
        cacheControl: String = "no-cache"
    ) async throws -> String {
        let session = try await NetworkClient.shared.auth.session
                
        guard let url = URL(string: "\(myUrl)/storage/v1/object/\(bucket)/\(path)") else {
            throw URLError(.badURL)
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue(myApiKey, forHTTPHeaderField: "apikey")
        request.setValue("Bearer \(session.accessToken)", forHTTPHeaderField: "Authorization")
        request.setValue("image/jpeg", forHTTPHeaderField: "Content-Type")
        request.setValue(cacheControl, forHTTPHeaderField: "Cache-Control")
        request.setValue(upsert.description, forHTTPHeaderField: "x-upsert")
        request.httpBody = data
        
        let (responseData, response) = try await URLSession.shared.data(for: request)
        
        if let httpResponse = response as? HTTPURLResponse, !(200...299).contains(httpResponse.statusCode) {
            throw URLError(.badServerResponse)
        }
        
        guard let json = try? JSONSerialization.jsonObject(with: responseData, options: []),
              let jsonObject = json as? [String: Any],
              let key = jsonObject["Key"] as? String else {
            throw URLError(.cannotParseResponse)
        }
        
        return key
    }
```

**Comment by grdsdev** [comment]
Hi @florian-mlr can you confirm you get `cache-control` other than `no-cache` when using your code?

I'm still doing a few tests and wasn't able to get `cache-control` other than `no-cache` as response.

**Comment by florian-mlr** [comment]
> Hi @florian-mlr can you confirm you get `cache-control` other than `no-cache` when using your code?
> 
> I'm still doing a few tests and wasn't able to get `cache-control` other than `no-cache` as response.

Hello @grdsdev !
Yes i can confirm it works with my code.

When checking on the browser, i get 
<img width="236" alt="Capture d’écran 2024-10-07 à 22 22 02" src="https://github.com/user-attachments/assets/67d784f2-7bd4-48e0-b693-29ff11a3edc0">

On your side, does my code work too ?

**Comment by grdsdev** [comment]
@florian-mlr when I download the file uploaded by your code, I still get `no-cache`, are you using download method from the library? How are you downloading it?
