### ISSUE TITLE
ErrorCode is missing invalid_grant

### ISSUE THREAD

**Issue by c128128** [supabase/supabase-swift#570]
Related with #543.

Here is the exact response from the server:
```json
{
	"error": "invalid_grant",
	"error_description": "Invalid login credentials"
}
```

**Comment by J0** [comment]
Hey @c128128,

Thanks for the query! Could you share with us the exact version of Supabase Auth in use? The error code should not exist on the latest version so hoping we could trouble you to share more so we can figure out what's going on together.

**Comment by c128128** [comment]
Hey @J0,

I am using this image `supabase/gotrue:v2.158.1`

**Comment by grdsdev** [comment]
@c128128 just confirming if you still need help with this, are you still facing issues?

**Comment by grdsdev** [comment]
Closing due inactivity, feel free to reopen it if you're still having issues
