### ISSUE TITLE
 Issue with "Main actor-isolated class property" in Supabase Swift Package

### ISSUE THREAD

**Issue by arekch444** [supabase/supabase-swift#571]
Hello,

I am encountering an issue with the Supabase Swift SDK in my iOS project, related to the Main actor-isolated class property.

Description of the issue:
While integrating the Supabase SDK into my iOS application, I encountered the following error:

"Main actor-isolated class property 'didBecomeActiveNotification' cannot be referenced from a non-isolated context"

This error appears in the AuthClient file within the NotificationCenter observer for the UIApplication.didBecomeActiveNotification and UIApplication.willResignActiveNotification. I am unable to directly modify this file as it is part of the Swift Package, and despite updating the package to the latest version, the issue persists.

Steps I took:
Installed the Supabase Swift package using Swift Package Manager.
Added the client configuration in my Xcode project.
Encountered the error mentioned above when trying to handle app lifecycle notifications.
I have verified that my project is using the latest version of the package, but the error still occurs.

Environment:
Xcode version: 15.2
Supabase Swift SDK version: 2.20.2
iOS target version: >17
Could you provide any guidance on how to resolve this issue, or if there is a patch planned to fix this?

Thank you for your assistance!

Best regards,

**Comment by wrkstries** [comment]
Thanks for raising this. I am also having the same issue.

**Comment by grdsdev** [comment]
Hi, thanks for reporting it, I'll take a look ASAP

**Comment by grdsdev** [comment]
This error occurs when using Xcode 15.2, and Swift 5.9, please if possible update Xcode to at least 15.4 (ideally to last version which is 16).

We're dropping support for Xcode 15.2 and Swift 5.9 soon, as Swift 6 has been released already.

Check our support policy https://github.com/supabase/supabase-swift?tab=readme-ov-file#support-policy

**Comment by marcprux** [comment]
This is hitting us as well. Our GitHub CI tests against macOS-13, for which the highest installable Xcode is 13.2, and we can't upgrade it for the foreseeable future (for unrelate reasons). I wonder if there might be a workaround that could be applied? Like adding `@MainActor` to the types in `AuthClient.swift`?

**Comment by grdsdev** [comment]
Got it @marcprux I'll push a fix for it.

Thanks.
