### ISSUE TITLE
authClient.session(from url: URL) has incorrect error when an error occurs during PKCE flow

### ISSUE THREAD

**Issue by MilesV64** [supabase/supabase-swift#591]
# Bug report
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When attempting to link an identity (specifically trying apple) via `linkIdentity`, if the flow has an error in the url, calling `authClient.session(from url: URL)` throws `AuthError.pkceGrantCodeExchange(message: "Not a valid PKCE flow url: \(url)")` when really it should parse the error params from the url first. I want the actual error message from the url, but it thinks it's not a PKCE url just because it doesn't have the code.

## To Reproduce

1. Call `linkIdentity` provider `.apple`
2. Sign in to an apple account that is already linked to another user
3. Give the redirect url (which will have error_message and error_code in it) to `authClient.session(from url: url)`
4. Throws `AuthError.pkceGrantCodeExchange(message: "Not a valid PKCE flow url: \(url)")`, but should throw the actual error in the url

## Expected behavior

If a PKCE flow encounters an error in the url, throw that error specifically rather than saying it's not a PKCE flow

## Additional context

Here's an example URL:

https://my.redirect.com?error=server_error&error_code=422&error_description=Identity+is+already+linked+to+another+user#error=server_error&error_code=422&error_description=Identity+is+already+linked+to+another+user

**Comment by grdsdev** [comment]
Hi @MilesV64 thanks for reporting this issue, I'll push a fix for it ASAP.
