### ISSUE TITLE
URLSessionTransport is only available in iOS 13 or newer, but not constrained to that in RealtimeClient

### ISSUE THREAD

**Issue by chFlorian** [supabase/supabase-swift#6]
# Bug report

## Describe the bug

URLSessionTransport is only available in iOS 13 or newer, but not constrained to that in RealtimeClient
What I find interesting is that the version constraint is commented out. Is this by accident?

## Screenshots

![image](https://user-images.githubusercontent.com/23061765/132164120-b279ed10-dd9c-4ab0-89ee-aa387421f2d7.png)

## System information

- OS: macOS
- Xcode 12
- Version of supabase-swift: none, this package is based off a branch, not versions

**Comment by satishbabariya** [comment]
@chFlorian already added the availability constraints please check this out, [https://github.com/supabase/realtime-swift/blob/242acdcbbf8c4f063c114831a3e7820c4dbf61a6/Sources/Realtime/RealtimeClient.swift#L160](RealtimeClient.swift)

**Comment by chFlorian** [comment]
Interesting. I just cloned supabase-swift and got this error. Let me clean package cache and look at it again.

**Comment by grsouza** [comment]
@chFlorian were you able to check it? Can I close this issue?

**Comment by chFlorian** [comment]
After manually updating the package it is fixed. No idea why Xcode fetched an old version of the package as I have never worked with it before.
