### ISSUE TITLE
Ambiguous use of 'compactMap'

### ISSUE THREAD

**Issue by dylan0356** [supabase/supabase-swift#606]
# Bug report

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

An empty xcode swiftui project with supabase installed will not build. This is before even having it initialized.

I am getting ```Ambiguous use of 'compactMap'``` error in 3 functions for in the RealtimeChannel+AsyncAwait.swift

```
  public func postgresChange(
    _: InsertAction.Type,
    schema: String = "public",
    table: String? = nil,
    filter: String? = nil
  ) -> AsyncStream<InsertAction> {
    postgresChange(event: .insert, schema: schema, table: table, filter: filter)
      .compactMap { $0.wrappedAction as? InsertAction } ERROR: Ambiguous use of 'compactMap'
      .eraseToStream()
  }
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new empty xcode project
2. Add Supabase as a repository
3. Try to build it

## Expected behavior

For it to work build...

## Screenshots

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/8866523c-e084-48b4-b08a-93acac364c8f">

## System information

- OS: MacOS

**Comment by grdsdev** [comment]
Hi, which Xcode version are you using?

**Comment by DevSynthx** [comment]
Got the same error .. I am using Xcode Version 15.0.1 @grdsdev

**Comment by byROCO** [comment]
Oh so it's really an error for everyone same using xcode version 15.0.1

**Comment by grdsdev** [comment]
I don't have Xcode 15.0.1 installed locally, but I added Xcode 15.0.1 to the CI and it is building fine https://github.com/supabase/supabase-swift/actions/runs/11956197767/job/33330387648?pr=607

Can you try cleaning derived data and all caches and trying again? Let me know if issue persists, and I'll try to get get Xcode 15.0.1 installed locally for testing.

**Comment by grdsdev** [comment]
Strange, CI runs on:
- macOS 14; Xcode 15.0.1
- macOS 14; Xcode 15.4
- macOS 15; Xcode 16

And all working fine, let me try on macOS 13

**Comment by grdsdev** [comment]
This workflow ran on macOS 13, Xcode 15.0.1 and passed https://github.com/supabase/supabase-swift/actions/runs/11961059909/job/33346456563?pr=607

If anyone has an idea on why this strange behavior is happening, I appreciate.

PS: It says macOS 14 but it is actually macOS 13

**Comment by marcprux** [comment]
Your CI is running `xcodebuild` on macOS, but the failure I'm seeing is from `swift build`. I guess there must be some subtle difference?

I made a simple action that just runs [`swift test`](https://github.com/marcprux/supabase-swift/blob/main/.github/workflows/ci-test.yml), and you can see [here](https://github.com/marcprux/supabase-swift/actions/runs/11962155375/job/33349899739#step:3:255) that it fails on macos-13.

**Comment by byROCO** [comment]
So i tried updating macos + Xcode, and it seems like the error is gone now.

**Comment by grdsdev** [comment]
Thanks for the fix @marcprux, please everyone update to latest v2.23.0 version.
