### ISSUE TITLE
How are we supposed to use Supabase Vault from the Swift library?

### ISSUE THREAD

**Issue by MadeByDouglas** [supabase/supabase-swift#623]
# Improve documentation

## Describe the problem

What's the correct way to access Supabase Vault from the swift client?

when I message the Supabase AI assistant, it suggests,

`let response = try await supabase.vault.get(...name of your key...)`

but of course that doesn't exist.

the Vault documentation mentions just using a postgres function, but its not clear to me how that would work.

Furthermore, other AI models suggest using rpc or an edge function, or even just query a table called "vault_secrets".

I can't find anything specific on the documentation site, and clear direction here would be appreciated.

## Describe the improvement

I'm assuming a postgres function and rpc is the way to do this, but I'm not sure how it handles https and the decryption

## Additional context

https://supabase.com/docs/guides/database/vault

**Comment by grdsdev** [comment]
Hi @MadeByDouglas,

There is no out-of-the-box way of accessing the vault from the Swift lib.

Could you share a bit more context on why are you trying to access Vault from Swift? What's the use case?

**Comment by MadeByDouglas** [comment]
Ah I see, ok well I created a Postgres function and then accessed that via rpc, which I guess seems to be the correct way. Maybe just a mention of this on the docs would be helpful. Also note key names are case sensitive, which nowhere in the docs mention this and that would have been nice to know.

I'm using it to store an API key securely on supabase and then send it to the swift client app via https, where the client app promptly saves it to the device keychain. It's a simple but effective way to avoid storing api keys on the client and keep them secure without needing a full reverse proxy server setup.

**Comment by grdsdev** [comment]
In that case, using the RPC is the way to do it from Swift, columns are decrypted transparently.

I'll make sure to review the docs, on the things you pointed out, thanks!
