### ISSUE TITLE
Signup with WhatsApp not Supported

### ISSUE THREAD

**Issue by inawafalm** [supabase/supabase-swift#624]
## Describe the bug

The documentation states that we can signup using the channel WhatsApp, however in the GitHub repository of the supabase, is not showing as mentioned in the documentation

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://supabase.com/docs/reference/swift/auth-signup'
2. Click on 'Sign up with a phone number and password (whatsapp)'
3. Try to implement this function in your swift code, it will show an error that it's an extra argument!

## Expected behavior

As expected in the documentation!

## Screenshots

<img width="758" alt="Screenshot 2024-12-16 at 7 43 35 AM" src="https://github.com/user-attachments/assets/8b10f09d-a7fd-41a7-a4df-f55317f4c7c7" />

## System information

- OS: MacOs
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase SDK : 2.24
- Version of iOS: 16/17/18

**Comment by grdsdev** [comment]
Thanks for reporting it, will push a fix soon.

**Comment by inawafalm** [comment]
Thank you! you are the best :)
